name: Render Wakeup

on:
  schedule:
    # 매 10분마다 실행
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping root domain (/healthz)
        run: |
          curl -fsS -m 15 -L https://yaro8583.cloud/healthz -o /dev/null -w "code=%{http_code}\n"
      - name: Ping www domain (/healthz)
        run: |
          curl -fsS -m 15 -L https://www.yaro8583.cloud/healthz -o /dev/null -w "code=%{http_code}\n"
